package env

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	"github.com/dotenv/cli/internal/formats"
)

// Generator implements ENV format generation
type Generator struct {
	options *formats.Options
}

// NewGenerator creates a new ENV generator
func NewGenerator(opts *formats.Options) *Generator {
	if opts == nil {
		opts = formats.DefaultOptions()
	}
	return &Generator{options: opts}
}

// Generate writes ENV format to a writer
func (g *Generator) Generate(w io.Writer, data map[string]string) error {
	keys := make([]string, 0, len(data))
	for k := range data {
		keys = append(keys, k)
	}

	// Sort keys if requested
	if g.options.SortKeys {
		sort.Strings(keys)
	}

	// Write header comment if requested
	if g.options.IncludeComments {
		header := []string{
			"# Generated by DotEnv CLI",
			"# https://dotenv.cloud",
			"",
		}
		for _, line := range header {
			if _, err := fmt.Fprintln(w, line); err != nil {
				return err
			}
		}
	}

	// Write each key-value pair
	for i, key := range keys {
		value := data[key]

		// Format the line
		line := g.formatLine(key, value)

		// Write line
		if _, err := fmt.Fprint(w, line); err != nil {
			return err
		}

		// Add line ending
		if i < len(keys)-1 || !strings.HasSuffix(line, g.options.LineEnding) {
			if _, err := fmt.Fprint(w, g.options.LineEnding); err != nil {
				return err
			}
		}
	}

	return nil
}

// GenerateString returns ENV format as a string
func (g *Generator) GenerateString(data map[string]string) (string, error) {
	var buf strings.Builder
	if err := g.Generate(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// GenerateFile writes ENV format to a file
func (g *Generator) GenerateFile(filename string, data map[string]string) error {
	file, err := os.Create(filename)
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	defer file.Close()

	return g.Generate(file, data)
}

// formatLine formats a single key-value pair
func (g *Generator) formatLine(key, value string) string {
	// Check if value needs quoting
	needsQuotes := g.options.QuoteValues || g.needsQuoting(value)

	if needsQuotes {
		value = g.quoteValue(value)
	}

	return fmt.Sprintf("%s=%s", key, value)
}

// needsQuoting determines if a value needs quotes
func (g *Generator) needsQuoting(value string) bool {
	if value == "" {
		return false
	}

	// Check for whitespace at start/end
	if value != strings.TrimSpace(value) {
		return true
	}

	// Check for special characters
	specialChars := []string{
		" ", "\t", "\n", "\r",
		"#", "$", "&", "|",
		";", "<", ">", "`",
		"(", ")", "[", "]",
		"{", "}", "*", "?",
		"!", "~", "\"", "'",
	}

	for _, char := range specialChars {
		if strings.Contains(value, char) {
			return true
		}
	}

	return false
}

// quoteValue properly quotes a value
func (g *Generator) quoteValue(value string) string {
	// Escape existing quotes and backslashes
	value = strings.ReplaceAll(value, "\\", "\\\\")
	value = strings.ReplaceAll(value, "\"", "\\\"")

	// Escape newlines and other control characters
	value = strings.ReplaceAll(value, "\n", "\\n")
	value = strings.ReplaceAll(value, "\r", "\\r")
	value = strings.ReplaceAll(value, "\t", "\\t")

	return fmt.Sprintf("\"%s\"", value)
}

// GenerateExtended generates with additional options
func (g *Generator) GenerateExtended(w io.Writer, result *formats.ParseResult, opts *formats.GenerateOptions) error {
	if opts == nil {
		opts = &formats.GenerateOptions{Options: g.options}
	}

	// Write header if provided
	if opts.Header != "" {
		lines := strings.Split(opts.Header, "\n")
		for _, line := range lines {
			if _, err := fmt.Fprintf(w, "# %s%s", line, opts.LineEnding); err != nil {
				return err
			}
		}
		if _, err := fmt.Fprint(w, opts.LineEnding); err != nil {
			return err
		}
	}

	// Determine key order
	keys := opts.KeyOrder
	if len(keys) == 0 {
		if len(result.Order) > 0 {
			keys = result.Order
		} else {
			keys = make([]string, 0, len(result.Data))
			for k := range result.Data {
				keys = append(keys, k)
			}
			if opts.SortKeys {
				sort.Strings(keys)
			}
		}
	}

	// Write key-value pairs
	for _, key := range keys {
		// Apply filter if provided
		if opts.KeyFilter != nil && !opts.KeyFilter(key) {
			continue
		}

		value, ok := result.Data[key]
		if !ok {
			continue
		}

		// Write comment if exists
		if comment, hasComment := result.Comments[key]; hasComment && opts.PreserveComments {
			if _, err := fmt.Fprintf(w, "# %s%s", comment, opts.LineEnding); err != nil {
				return err
			}
		}

		// Write key-value
		line := g.formatLine(key, value)
		if _, err := fmt.Fprintf(w, "%s%s", line, opts.LineEnding); err != nil {
			return err
		}
	}

	return nil
}
